name: flutter_8_bit_cpu_simulator
description: "A 8-bit CPU simulator built with Flutter."

publish_to: "none"

version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  fluentui_system_icons: ^1.1.273
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSansCode
      fonts:
        - asset: assets/fonts/GoogleSansCode-Light.ttf
          weight: 300
        - asset: assets/fonts/GoogleSansCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSansCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSansCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSansCode-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSansCode-ExtraBold.ttf
          weight: 800
